### ISSUE TITLE
Doesn't work in Sketch 66

### ISSUE THREAD

**Issue by Delloss** [aparajita/sketch-style-master#15]
Hey, it seems that the plugin doesn't work with the new version of Sketch 66. It won't even open the panel with styles. Can you please take a look at it?

[Screen Recording.zip](https://github.com/aparajita/sketch-style-master/files/4661374/Screen.Recording.zip)

**Comment by aparajita** [comment]
The plugin API changed. I don't have a ton of time to work on this, so please be patient.

**Comment by iNorthSea** [comment]
> The plugin API changed. I don't have a ton of time to work on this, so please be patient.

Thank you so much.

**Comment by staffdefer** [comment]
Thank you! Love this plugin.

**Comment by abinashmohanty** [comment]
> The plugin API changed. I don't have a ton of time to work on this, so please be patient.

It's one of the best plugins I'm using in order to find and replace both text and layer styles. And I don't mind buying it. Just count me in. 🤟🏻

**Comment by staffdefer** [comment]
> > The plugin API changed. I don't have a ton of time to work on this, so please be patient.
> 
> It's one of the best plugins I'm using in order to find and replace both text and layer styles. And I don't mind buying it. Just count me in. 🤟🏻

Count me in aswell! 💪

**Comment by garethmtm** [comment]
Not working on 67.2 either :( Would love to give it a try though, looks great!

**Comment by josh-tt** [comment]
Can confirm, not working 

> > > The plugin API changed. I don't have a ton of time to work on this, so please be patient.
> > 
> > 
> > It's one of the best plugins I'm using in order to find and replace both text and layer styles. And I don't mind buying it. Just count me in. 🤟🏻
> 
> Count me in aswell! 💪

Me too.  This is the only plugin I've found to remedy issues with style names.  Would be happy to pay. 

It works with 6.51 in case anyone needs it, you can download it from the Sketch website. Just be careful not to open newer files with that version as it might corrupt your project. So far, it's worked fine for me though.

**Comment by aparajita** [comment]
v1.0.5 works, thanks to @symdesign for the help.

**Comment by josh-tt** [comment]
Great news, thank you 🙏
