### ISSUE TITLE
Not working in Sketch 61.1

### ISSUE THREAD

**Issue by davidmcneroe86** [aparajita/sketch-style-master#16]
When I try open plugin it doesn't launch in Sketch 61.1

So, Plugins > Style Master > Rename Text Styles....and the window doesn't open

Thanks

**Comment by staffdefer** [comment]
Same for me. Please fix, I love this plugin <3.

**Comment by aparajita** [comment]
Duplicate of #15

**Comment by aparajita** [comment]
v1.0.5 works with Sketch 66+, but no longer with older versions. Sketch 61 is ancient, sorry, I can't support everything.

**Comment by davidmcneroe86** [comment]
Thanks, seems to work now with the update!
