### ISSUE TITLE
suggestion: New feature or similar plugin for renaming artboards / layers

### ISSUE THREAD

**Issue by Arkkimaagi** [aparajita/sketch-style-master#2]
I really love your plugin, the preview feature beats the other plugins to the ground.

What I'm missing, is a similar plugin or an extension to this one that would search and replace from artboard/layer names with a preview and the regex features. (I know my regex, but maybe a couple of tips would be in order if someone enables the regex in current plugin)

This would make it so much easier to reorganise my symbols without the fear of messing something up.

At start it would be enough to search through all the artboards/layers on the current page. Maybe in future one could search from current page / all pages.

**Comment by aparajita** [comment]
http://rodi01.github.io/RenameIt/

**Comment by Arkkimaagi** [comment]
I am disappointed at your reply.

Of course I have found renameit. It does not solve the problem as elegantly as your plugin does.

Furthermore, it does not have as nice or logical preview feature. Nor does it have regex for replacing. (That I found of at least)

**Comment by aparajita** [comment]
Let me explain something: I spent something like two weeks of my valuable time making this plugin. Time that I could have (and should have) spent doing paid work for a client. When I finished the plugin, I realized it wasn’t fair for me to spend time on personal projects when a good client was waiting for me to finish their project.

I see you have also made some Sketch plugins. Please don’t ask me to fulfill your wishes, fork this repo and do whatever you want. That’s why it’s open source.

**Comment by Arkkimaagi** [comment]
I am sorry, did not mean to offend you.

Like you noticed, I do have sketch plugins myself and I do appreciate feedback and ideas when given with enough details for me to understand what the other person is requesting. When I get motivated or exited about the idea, I'll work on it when I get the time.

Of course not all requests will be accepted and that's how it is. No harm in asking. I try to give replies about the ideas and implement them if I personally want. As you can probably see, my own repos do have some ideas I have not implemented yet, maybe someday I will.

I was disappointed at your reply as I felt that maybe you did not understand what I was trying to say or chose to ignore it on purpose. I could not decipher which was the case. So I tried to clarify that I indeed had found the plugin you linked, and many more. None of them came close to what you have here. (Good job on your code!)

Sure, I can clone your code as it is open source. (Thanks for that btw) I just wanted to first contact you with the idea, maybe it was something you were interested in, were already working on, or knew about a way to do with another solution. I had no idea about the background why and how long this plugin was made.

Maybe I will develop said functionality on my own based on your code. (I'll of course give credit back to you if I do) I totally understand the time dilemma for developing FOSS as I am too quite busy with a new baby and all.

Sorry for the trouble, I'll not bother you anymore.

All the best,
Mikko

**Comment by aparajita** [comment]
Actually it’s my fault for not saying clearly in the README that the project is no longer being maintained. I understood what you were asking for, I should have said, “Sorry, I am no longer maintaining this, RenameIt more or less does what you want.”

**Comment by AdamSabla** [comment]
@aparajita I was just about to create the same issue as this one.

I fully understand your point of view.

Haven't you considered to making this plugin a paid product? You could sell it via gumroad.com, It's very easy.

This is such a good plugin, it saved us hours of time. I would have no problem paying $200 for such a plugin. It comes handy when working on a huge project, so the time it can save in those cases is huge. That way, a price tag this big can be easily justified ($50-200 no problem, if you would add renaming layers / symbols / artboards / etc, the price could be even higher, or you could sell it as a separate plugin). Time = money. I'd be happy to pay.

There would not be many sales, but if someone really needs it, it's worth to pay for it.

Big companies have no problem to pay such money. We are in business of After Effects plugins, it's very similar.

Renamit won't do the trick. Your plugin rocks ;)

**Comment by aparajita** [comment]
@AdamSabla Thanks for the feedback. I can't think about this for a while, I'm too busy with client work.

I've got 142 stars right now. Even if half of those people were willing to pay $50, that's only $3500. But those who already have it aren't going to pay.

There are only a handful of paid Sketch plugins on gumroad, and the most expensive ones are $20. Would a $50 plugin really work?

To add renaming of layers and so on and do all of the work to make it commercial, I would have to spend another 30 hours at least. I'd have to sell at least 100 copies at $50 to make it worth it. I don't see how that can happen.

**Comment by AdamSabla** [comment]
@aparajita thanks for taking time to reply!

If it would work - hard to say. If you won't try, you won't find out :) But generally speaking, well targeted plugins can be expensive.

$50 is too little. I would price it to at least $99 or even $149. It's a niche target group.

**Comment by aparajita** [comment]
> If you won't try, you won't find out

I don't have any spare time or energy to spend on it, so it will have to remain in the land of dreams.
