### ISSUE TITLE
Request: Retain Find/Replace fields after Apply or Rename

### ISSUE THREAD

**Issue by seandellis** [aparajita/sketch-style-master#3]
Thank you so much for creating this plugin! It's been a huge lifesaver when creating a complicated set of text styles.

I've found that I often need to repeat my Find/Replace pattern with a small adjustment. It would be really helpful if after you've selected Apply or Rename that it retained what was last entered in the Find and Replace fields.

**Comment by aparajita** [comment]
I have no time to maintain this plugin unfortunately, but you can easily make the change yourself:

- Open Preferences, then click the Plugins tab.
- Right click on Style Master and select Show in Finder.
- In Contents/Sketch, open plugin.js.
- Comment out (add "//" at the beginning) these lines: https://github.com/aparajita/sketch-style-master/blob/34c7c15f19a3ff9613145d31818478cb2dbc5204/Style%20Master.sketchplugin/Contents/Sketch/plugin.js#L275-L277

That should do it. You might want to keep a copy of the modified plugin somewhere else, just in case your changes get lost by a reinstall.

**Comment by seandellis** [comment]
@aparajita Awesome! That did it. Thank you for your help and have a wonderful day!
