### ISSUE TITLE
Renaming Text Styles in Sketch 50 doesn't seem to work properly

### ISSUE THREAD

**Issue by bromso** [aparajita/sketch-style-master#4]
Hallelujah for this plugin! I _LOVE_ it!
With the new Sketch 50 update the plugin doesn't seem to work properly. I can start the plugin, perform searches but when I press 'Rename' it only renames one Text style (most likely the first one in the list). Any thoughts? :)

Thanks again for a awesome plugin!

**Comment by aparajita** [comment]
I'll push the fixed version out this weekend, in the meantime download this version and install it:

[Style Master.sketchplugin.zip](https://github.com/aparajita/sketch-style-master/files/2011263/Style.Master.sketchplugin.zip)

**Comment by aparajita** [comment]
Just pushed the fixed version, it should show up in Sketch.
