### ISSUE TITLE
Adding text before any layer that contains a certain word?

### ISSUE THREAD

**Issue by skillaentertain** [aparajita/sketch-style-master#6]
Hey Aparajita, thanks for your work on the Sketch Style Master! It's really helpful. 

Well, acutally it would be really helpful – but I struggle with a specific command:

There's tons of style layers in my sketch file (from a downloaded pack) which are not grouped in any way. They have names such as "001 Warm Style" and "002 Night Style"... Each of them starts with a number (ranging from 001 to 200) and ends with "Style".

Now I want to add "Gradient/" previous to all of these layer styles. 

But I really struggle to find a regex way to do so. Do you have any idea? I can imagine that it would be really helpful to lots of users if the plugin provided such preset-settings from scratch. 

Thanks for your help!

Kind regards
skillaentertain

**Comment by aparajita** [comment]
You want to prefix "Gradient/" to all names, or only those that begin with 3 numbers followed by a space?

In the first case:
Find: ^.+$
Replace: Gradient/$&

In the second case:
Find: ^\d{3} .+$
Replace: Gradient/$&

**Comment by skillaentertain** [comment]
You are brilliant. Thanks!
