### ISSUE TITLE
Rename Text Styles Duplicates the names of the text styles

### ISSUE THREAD

**Issue by CarmenAlia** [aparajita/sketch-style-master#7]
Hi there,
I've been using the plugin to map the relationship between my previous text style and the new ones.
I've changed text names and colour names. For the text names it's worked fine but it duplicates the name of the colours.

Please see the image.
![rename_text_styles_and_symbols-darci](https://user-images.githubusercontent.com/9437128/48022677-b0c3be00-e133-11e8-9e16-73e462a5dc3a.png)

**Comment by aparajita** [comment]
What version of Sketch?

**Comment by CarmenAlia** [comment]
Hi Aparajita,

I'm at version 51.3

**Comment by aparajita** [comment]
Well, they're all just text style names, I have no way of knowing what they represent. Without knowing what your find and replace strings and options were and the original names it's hard to know what went wrong.

**Comment by aparajita** [comment]
Closing this, without more info I can't do much.
