### ISSUE TITLE
Doesn't work in Sketch 53.2

### ISSUE THREAD

**Issue by dlewand691** [aparajita/sketch-style-master#9]
The panel opens and can search styles but when clicking Apply or Rename no changes are made. Any fix? Thank you!

**Comment by aparajita** [comment]
Working fine for me in Sketch 54. How about you?

**Comment by lmjabreu** [comment]
It does work for my on sketch 54.2, but there's a rendering issue when "Show only matching styles" is deselected, the "After" list is clipped and the "Before" doesn't display all matches in bold.

**Comment by aparajita** [comment]
Working perfectly here, can you send a screenshot of the entire dialog?

**Comment by lmjabreu** [comment]
<img width="1286" alt="Screenshot 2019-05-13 at 17 03 21" src="https://user-images.githubusercontent.com/40119971/57636475-1c825a00-75a1-11e9-8425-9e5c04eb2edc.png">

Notice how "Text" matches stop being highlighted in the before list, where the matches stop is where the scroll view went off-screen and I scrolled to reveal. Ticking and unticking "Show only matching styles" will update the scroll view to render the results properly.

**Comment by aparajita** [comment]
Fixed in 1.0.3.
